const KEY='wortsprint-v1';
const DAY=86400000;
const $=s=>document.querySelector(s);
let state=JSON.parse(localStorage.getItem(KEY)||'{"cards":{},"last":"","streak":0}');
let session=[],newWords=[],missedWords=[],learnIndex=0,index=0,correct=0,currentResult=false,selectedArticle='',selectedCase='';
const norm=s=>s.toLocaleLowerCase('de').trim().replace(/[.,!?]/g,'').replace(/\s+/g,' ');
function card(w){return state.cards[w.id]||{due:0,interval:0,reps:0,lapses:0}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function updateStreak(){const today=new Date().toISOString().slice(0,10);if(state.last===today)return;const yesterday=new Date(Date.now()-DAY).toISOString().slice(0,10);state.streak=state.last===yesterday?(state.streak||0)+1:1;state.last=today;save()}
function dueWords(pool=WORDS){const now=Date.now();return pool.filter(w=>state.cards[w.id]&&card(w).due<=now)}
function render(){const topic=$('#topic').value||'Wszystkie';const pool=WORDS.filter(w=>topic==='Wszystkie'||w.topic===topic);$('#dueCount').textContent=dueWords(pool).length;$('#total').textContent=WORDS.length;$('#known').textContent=WORDS.filter(w=>card(w).interval>=14).length;$('#learning').textContent=Object.keys(state.cards).length-Number($('#known').textContent);$('#streak').textContent=`${state.streak||0} dni 🔥`}
function init(){const topics=['Wszystkie',...new Set(WORDS.map(w=>w.topic))];$('#topic').innerHTML=topics.map(t=>`<option>${t}</option>`).join('');render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')}
function shuffle(items){for(let i=items.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[items[i],items[j]]=[items[j],items[i]]}return items}
function choose(){const t=$('#topic').value,size=$('#size').value,n=size==='random'?8+Math.floor(Math.random()*5):Number(size),pool=WORDS.filter(w=>t==='Wszystkie'||w.topic===t);const due=shuffle(dueWords(pool));const unseen=shuffle(pool.filter(w=>!state.cards[w.id]));const selected=due.slice(0,n);selected.push(...unseen.slice(0,n-selected.length));return shuffle(selected)}
function start(){session=choose();newWords=session.filter(w=>!state.cards[w.id]);missedWords=[];learnIndex=0;index=0;correct=0;if(!session.length)return;$('#home').hidden=true;$('#summary').hidden=true;if(newWords.length){$('#learn').hidden=false;$('#quiz').hidden=true;showLearn()}else{beginQuiz()}}
function showLearn(){const w=newWords[learnIndex];$('#learnProgress').textContent=`${learnIndex+1} z ${newWords.length} nowych`;$('#learnBar').style.width=`${(learnIndex+1)/newWords.length*100}%`;$('#learnTopic').textContent=w.topic;$('#learnGerman').textContent=w.de;$('#learnPolish').textContent=w.pl;$('#learnExtra').textContent=w.extra?`Liczba mnoga: ${w.extra}`:w.grammarCase?`Rekcja: + ${w.grammarCase==='dat'?'Dat.':'Akk.'}`:'Kliknij dalej, a za chwilę spróbujesz wpisać to słowo z pamięci.'}
function nextLearn(){learnIndex++;if(learnIndex<newWords.length)showLearn();else beginQuiz()}
function beginQuiz(){$('#learn').hidden=true;$('#quiz').hidden=false;session=shuffle(session);index=0;show()}
function nounParts(w){const match=w.de.match(/^(der|die|das)\s+([^\s]+)$/i);return match?{article:match[1].toLowerCase(),word:match[2]}:null}
function selectArticle(article){selectedArticle=article;document.querySelectorAll('[data-article]').forEach(b=>b.classList.toggle('selected',b.dataset.article===article));$('#answer').focus()}
function selectCase(value){selectedCase=value;document.querySelectorAll('[data-case]').forEach(b=>b.classList.toggle('selected',b.dataset.case===value));$('#answer').focus()}
function show(){const w=session[index],noun=nounParts(w);selectedArticle='';selectedCase='';$('#progressText').textContent=`${index+1} z ${session.length}`;$('#progressBar').style.width=`${index/session.length*100}%`;$('#cardTopic').textContent=w.topic;$('#prompt').textContent=w.pl;$('#answerForm').hidden=false;$('#feedback').hidden=true;$('#articleChoices').hidden=!noun;$('#caseChoices').hidden=!w.grammarCase;document.querySelectorAll('[data-article],[data-case]').forEach(b=>b.classList.remove('selected'));$('#answer').value='';$('#answer').placeholder=noun?'Wpisz rzeczownik bez rodzajnika…':'Wpisz odpowiedź…';$('#answer').focus()}
function check(e){e.preventDefault();const w=session[index],noun=nounParts(w),typed=norm($('#answer').value);let wordOk,articleOk=true,caseOk=true;if(noun){const typedWord=typed.replace(/^(der|die|das)\s+/,'');wordOk=typedWord===norm(noun.word);articleOk=selectedArticle===noun.article}else{wordOk=typed===norm(w.de)}if(w.grammarCase)caseOk=selectedCase===w.grammarCase;currentResult=wordOk&&articleOk&&caseOk;if(currentResult)correct++;else if(!missedWords.some(x=>x.id===w.id))missedWords.push(w);if(currentResult){$('#verdict').textContent='Dobrze!'}else if(noun&&wordOk&&!articleOk){$('#verdict').textContent=`Słowo dobrze, ale rodzajnik to „${noun.article}”`}else if(w.grammarCase&&wordOk&&!caseOk){$('#verdict').textContent=`Słowo dobrze, ale poprawna rekcja to + ${w.grammarCase==='dat'?'Dat.':'Akk.'}`}else if(noun&&!wordOk&&articleOk){$('#verdict').textContent='Rodzajnik dobrze, sprawdź słowo'}else{$('#verdict').textContent='Sprawdź odpowiedź'}const no=$('[data-grade="0"]'),almost=$('[data-grade="1"]'),easy=$('[data-grade="2"]');no.hidden=currentResult;almost.hidden=!currentResult;easy.hidden=!currentResult;no.textContent='Powtórz w tej rundzie';almost.textContent='Z trudem';easy.textContent='Łatwo';$('#verdict').style.color=currentResult?'#7be1ad':'#ef9a8d';$('#correctAnswer').textContent=w.de;$('#hint').textContent=w.extra?`Liczba mnoga: ${w.extra}`:w.grammarCase?`Rekcja: + ${w.grammarCase==='dat'?'Dat.':'Akk.'}`:'';$('#answerForm').hidden=true;$('#articleChoices').hidden=true;$('#caseChoices').hidden=true;$('#feedback').hidden=false}
function grade(g){if(!currentResult)g=0;const w=session[index],c=card(w),now=Date.now();if(g===0){c.interval=1;c.reps=0;c.lapses++;c.due=now+10*60000}else if(g===1){c.interval=Math.max(1,Math.round((c.interval||1)*1.7));c.reps++;c.due=now+c.interval*DAY}else{c.interval=c.reps===0?2:c.reps===1?6:Math.max(10,Math.round(c.interval*2.3));c.reps++;c.due=now+c.interval*DAY}state.cards[w.id]=c;updateStreak();save();index++;if(index<session.length)show();else finish()}
function finish(){$('#quiz').hidden=true;$('#summary').hidden=false;$('#score').textContent=`${correct}/${session.length}`;const missed=missedWords.length,left=dueWords(WORDS).length;$('#summaryTitle').textContent=missed?'Najpierw poprawmy błędy':left?'Runda skończona':'Cel na dziś osiągnięty!';$('#summaryText').textContent=missed?`${missed} słów do przećwiczenia`:left?`poprawnych · zostało ${left} powtórek`:'poprawnych odpowiedzi';$('#again').textContent=missed?'Powtórz błędne':left?'Następna runda':'Wróć';render()}
function continueAfterSummary(){if(missedWords.length){session=shuffle([...missedWords]);missedWords=[];correct=0;index=0;$('#summary').hidden=true;beginQuiz()}else{$('#summary').hidden=true;$('#home').hidden=false;render()}}
$('#start').onclick=start;$('#answerForm').onsubmit=check;document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>grade(Number(b.dataset.grade)));$('#quit').onclick=()=>{if(confirm('Zakończyć bieżącą sesję?')){finish()}};$('#again').onclick=()=>{$('#summary').hidden=true;$('#home').hidden=false;render()};$('#topic').onchange=render;$('#reset').onclick=()=>{if(confirm('Usunąć wszystkie zapisane postępy?')){localStorage.removeItem(KEY);state={cards:{},last:'',streak:0};render()}};init();
